refactor: change references from "welcome" to "radxa-welcome"
radxa-pkg/radxa-welcome pull request #1
Opened 2024-06-27 09:41 UTC by RadxaPanda

2024-06-27 09:44 UTC, RadxaYuntian requested changes

2024-06-27 09:44 UTC, RadxaYuntian commented on radxa-welcome
> +python3 /usr/share/radxa-welcome/launch.py
```suggestion
python3 /usr/share/radxa-welcome/launch.py

```

2024-06-27 10:13 UTC, RadxaPanda commented
now it should actually be ready for merge

2024-06-27 10:59 UTC, RadxaYuntian requested changes
Squash then I can merge.

2024-06-28 08:08 UTC, RadxaYuntian approved these changes

2024-06-28 08:08 UTC, merged